version: '3'
services:
  reactjs-gazin:
    container_name: react-app-gazin
    build: ./frontend
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - nodejs-gazin
    networks:
      - app-connect
    ports:
      - '3000:3000'

  nodejs-gazin:
    container_name: nodejs-gazin
    build: ./backend
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    environment:
      PORT: 3333
      POSTGRES_HOST: postgres-gazin
      POSTGRES_PORT: 5432
      POSTGRES_NAME: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres-gazin
    networks:
      - app-connect
    ports:
      - '3333:3333'

  postgres-gazin:
    container_name: postgres-gazin
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/data
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-connect
    ports:
      - '5432:5432'

volumes:
  postgres-data:

networks:
  app-connect:
    driver: bridge
